
const row1En = [
    ["`", "~"],
    ["1", "!"],
    ["2", "@"],
    ["3", "#"],
    ["4", "$"],
    ["5", "%"],
    ["6", "^"],
    ["7", "&"],
    ["8", "*"],
    ["9", "("],
    ["0", ")"],
    ["-", "_"],
    ["=", "+"],
    ["Backspace", "Backspace"],

    ["Tab", "Tab"],
    ["q", "Q"],
    ["w", "W"],
    ["e", "E"],
    ["r", "R"],
    ["t", "T"],
    ["y", "Y"],
    ["u", "U"],
    ["i", "I"],
    ["o", "O"],
    ["p", "P"],
    ["[", "{"],
    ["]", "}"],
    ["\\", "|"],
    ["Del", "Del"],

    ["CapsLock", "CapsLock"],
    ["a", "A"],
    ["s", "S"],
    ["d", "D"],
    ["f", "F"],
    ["g", "G"],
    ["h", "H"],
    ["j", "J"],
    ["k", "K"],
    ["l", "L"],
    [";", ":"],
    ["'", '"'],
    ["Enter", "Enter"],
   
    
    ["Shift", "Shift"],
    ["z", "Z"],
    ["x", "X"],
    ["c", "C"],
    ["v", "V"],
    ["b", "B"],
    ["n", "N"],
    ["m", "M"],
    [",", "<"],
    [".", ">"],
    ["/", "?"],
    ["▲", "▲"],
    ["Shift", "Shift"],
    

    ["Ctrl", "Ctrl"],
    ["Win", "Win"],
    ["Alt", "Alt"],
    [" ", " "],
    ["Alt", "Alt"],
    ["◄", "◄"],
    ["▼", "▼"],
    ["►", "►"],
    ["Ctrl", "Ctrl"],


  ];
const row1Ru = [
    ["ё", "Ё"],
    ["1", "!"],
    ["2", "'"],
    ["3", "#"],
    ["4", "$"],
    ["5", "%"],
    ["6", "^"],
    ["7", "&"],
    ["8", "*"],
    ["9", "("],
    ["0", ")"],
    ["-", "_"],
    ["=", "+"],
    ["Backspace", "Backspace"],

    ["Tab", "Tab"],
    ["й", "Й"],
    ["ц", "Ц"],
    ["у", "У"],
    ["к", "К"],
    ["е", "Е"],
    ["н", "Н"],
    ["г", "Г"],
    ["ш", "Ш"],
    ["щ", "Щ"],
    ["з", "З"],
    ["х", "Х"],
    ["ъ", "Ъ"],
    ["\\", "|"],
    ["Del", "Del"],

    ["CapsLock", "CapsLock"],
    ["ф", "Ф"],
    ["ы", "Ы"],
    ["в", "В"],
    ["а", "А"],
    ["п", "П"],
    ["р", "Р"],
    ["о", "О"],
    ["л", "Л"],
    ["д", "Д"],
    ["ж", "Ж"],
    ["э", 'Э'],
    ["Enter", "Enter"],
   
    ["Shift", "Shift"],
    ["я", "Я"],
    ["ч", "Ч"],
    ["с", "С"],
    ["м", "М"],
    ["и", "И"],
    ["т", "Т"],
    ["ь", "Ь"],
    ["б", "Б"],
    ["ю", "Ю"],
    [".", ","],
    ["▲", "▲"],
    ["Shift", "Shift"],
    

    ["Ctrl", "Ctrl"],
    ["Win", "Win"],
    ["Alt", "Alt"],
    [" ", " "],
    ["Alt", "Alt"],
    ["◄", "◄"],
    ["▼", "▼"],
    ["►", "►"],
    ["Ctrl", "Ctrl"],


  ];

  const keyCode = ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal', 'Backspace', 'Tab', 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash', 'Delete', 'CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter', 'ShiftLeft', 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ArrowUp', 'ShiftRight', 'ControlLeft', 'MetaLeft', 'AltLeft', 'Space', 'AltRight', 'ArrowLeft', 'ArrowDown', 'ArrowRight', 'ControlRight']

  export { row1En as dataEn, row1Ru as dataRu, keyCode as code };